#!/usr/bin/env python3

from sys import exit
from pbench.common import configtools


def main():
    opts, args = configtools.parse_args(
        configtools.options,
        usage="Usage: getconf.py [options] <item>|-a <section> [<section> ...]",
    )
    conf, files = configtools.init(opts, "_PBENCH_AGENT_CONFIG")
    status = configtools.main(conf, args, opts, files)
    exit(status)


if __name__ == "__main__":
    main()
